/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 male_4.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Male4(props) {
    const { nodes, materials } = useGLTF('/3D/male_4.gltf')
    return (
        <group {...props} dispose={null} position={[-0.3, 0, -0.5]}>
            <group rotation={[Math.PI / 2, 0, 0]}>
                <primitive object={nodes.Root} />
            </group>
            <skinnedMesh
                geometry={nodes.male_accessory.geometry}
                material={materials.Palette}
                skeleton={nodes.male_accessory.skeleton}
            />
            <skinnedMesh
                geometry={nodes.male_hat.geometry}
                material={materials.Palette}
                skeleton={nodes.male_hat.skeleton}
            />
            <skinnedMesh
                geometry={nodes.male_hair.geometry}
                material={materials.Palette}
                skeleton={nodes.male_hair.skeleton}
            />
            <skinnedMesh
                name="male_forearm"
                geometry={nodes.male_forearm.geometry}
                material={materials.Palette}
                skeleton={nodes.male_forearm.skeleton}
                morphTargetDictionary={nodes.male_forearm.morphTargetDictionary}
                morphTargetInfluences={nodes.male_forearm.morphTargetInfluences}
            />
            <skinnedMesh
                name="male_head"
                geometry={nodes.male_head.geometry}
                material={materials.Palette}
                skeleton={nodes.male_head.skeleton}
                morphTargetDictionary={nodes.male_head.morphTargetDictionary}
                morphTargetInfluences={nodes.male_head.morphTargetInfluences}
            />
            <skinnedMesh
                name="male_pants"
                geometry={nodes.male_pants.geometry}
                material={materials.Palette}
                skeleton={nodes.male_pants.skeleton}
                morphTargetDictionary={nodes.male_pants.morphTargetDictionary}
                morphTargetInfluences={nodes.male_pants.morphTargetInfluences}
            />
            <skinnedMesh
                name="male_shirt"
                geometry={nodes.male_shirt.geometry}
                material={materials.Palette}
                skeleton={nodes.male_shirt.skeleton}
                morphTargetDictionary={nodes.male_shirt.morphTargetDictionary}
                morphTargetInfluences={nodes.male_shirt.morphTargetInfluences}
            />
            <skinnedMesh
                name="male_shoes"
                geometry={nodes.male_shoes.geometry}
                material={materials.Palette}
                skeleton={nodes.male_shoes.skeleton}
                morphTargetDictionary={nodes.male_shoes.morphTargetDictionary}
                morphTargetInfluences={nodes.male_shoes.morphTargetInfluences}
            />
            {/* <group rotation={[Math.PI / 2, 0, 0]}>
        <primitive object={nodes.Root_1} />
      </group>
      <skinnedMesh geometry={nodes.male_hat_1.geometry} material={materials.Palette} skeleton={nodes.male_hat_1.skeleton} />
      <skinnedMesh geometry={nodes.male_hair_1.geometry} material={materials.Palette} skeleton={nodes.male_hair_1.skeleton} />
      <skinnedMesh name="male_forearm_1" geometry={nodes.male_forearm_1.geometry} material={materials.Palette} skeleton={nodes.male_forearm_1.skeleton} morphTargetDictionary={nodes.male_forearm_1.morphTargetDictionary} morphTargetInfluences={nodes.male_forearm_1.morphTargetInfluences} />
      <skinnedMesh name="male_head_1" geometry={nodes.male_head_1.geometry} material={materials.Palette} skeleton={nodes.male_head_1.skeleton} morphTargetDictionary={nodes.male_head_1.morphTargetDictionary} morphTargetInfluences={nodes.male_head_1.morphTargetInfluences} />
      <skinnedMesh name="male_pants_1" geometry={nodes.male_pants_1.geometry} material={materials.Palette} skeleton={nodes.male_pants_1.skeleton} morphTargetDictionary={nodes.male_pants_1.morphTargetDictionary} morphTargetInfluences={nodes.male_pants_1.morphTargetInfluences} />
      <skinnedMesh name="male_shirt_1" geometry={nodes.male_shirt_1.geometry} material={materials.Palette} skeleton={nodes.male_shirt_1.skeleton} morphTargetDictionary={nodes.male_shirt_1.morphTargetDictionary} morphTargetInfluences={nodes.male_shirt_1.morphTargetInfluences} />
      <skinnedMesh name="male_shoes_1" geometry={nodes.male_shoes_1.geometry} material={materials.Palette} skeleton={nodes.male_shoes_1.skeleton} morphTargetDictionary={nodes.male_shoes_1.morphTargetDictionary} morphTargetInfluences={nodes.male_shoes_1.morphTargetInfluences} />
      <group rotation={[Math.PI / 2, 0, 0]}>
        <primitive object={nodes.Root_2} />
      </group>
      <skinnedMesh geometry={nodes.male_hat_2.geometry} material={materials.Palette} skeleton={nodes.male_hat_2.skeleton} />
      <skinnedMesh geometry={nodes.male_hair_2.geometry} material={materials.Palette} skeleton={nodes.male_hair_2.skeleton} />
      <skinnedMesh name="male_forearm_2" geometry={nodes.male_forearm_2.geometry} material={materials.Palette} skeleton={nodes.male_forearm_2.skeleton} morphTargetDictionary={nodes.male_forearm_2.morphTargetDictionary} morphTargetInfluences={nodes.male_forearm_2.morphTargetInfluences} />
      <skinnedMesh name="male_head_2" geometry={nodes.male_head_2.geometry} material={materials.Palette} skeleton={nodes.male_head_2.skeleton} morphTargetDictionary={nodes.male_head_2.morphTargetDictionary} morphTargetInfluences={nodes.male_head_2.morphTargetInfluences} />
      <skinnedMesh name="male_pants_2" geometry={nodes.male_pants_2.geometry} material={materials.Palette} skeleton={nodes.male_pants_2.skeleton} morphTargetDictionary={nodes.male_pants_2.morphTargetDictionary} morphTargetInfluences={nodes.male_pants_2.morphTargetInfluences} />
      <skinnedMesh name="male_shirt_2" geometry={nodes.male_shirt_2.geometry} material={materials.Palette} skeleton={nodes.male_shirt_2.skeleton} morphTargetDictionary={nodes.male_shirt_2.morphTargetDictionary} morphTargetInfluences={nodes.male_shirt_2.morphTargetInfluences} />
      <skinnedMesh name="male_shoes_2" geometry={nodes.male_shoes_2.geometry} material={materials.Palette} skeleton={nodes.male_shoes_2.skeleton} morphTargetDictionary={nodes.male_shoes_2.morphTargetDictionary} morphTargetInfluences={nodes.male_shoes_2.morphTargetInfluences} />
      <group rotation={[Math.PI / 2, 0, 0]}>
        <primitive object={nodes.Root_3} />
      </group>
      <skinnedMesh geometry={nodes.male_hat_3.geometry} material={materials.Palette} skeleton={nodes.male_hat_3.skeleton} />
      <skinnedMesh geometry={nodes.male_hair_3.geometry} material={materials.Palette} skeleton={nodes.male_hair_3.skeleton} />
      <skinnedMesh name="male_forearm_3" geometry={nodes.male_forearm_3.geometry} material={materials.Palette} skeleton={nodes.male_forearm_3.skeleton} morphTargetDictionary={nodes.male_forearm_3.morphTargetDictionary} morphTargetInfluences={nodes.male_forearm_3.morphTargetInfluences} />
      <skinnedMesh name="male_head_3" geometry={nodes.male_head_3.geometry} material={materials.Palette} skeleton={nodes.male_head_3.skeleton} morphTargetDictionary={nodes.male_head_3.morphTargetDictionary} morphTargetInfluences={nodes.male_head_3.morphTargetInfluences} />
      <skinnedMesh name="male_pants_3" geometry={nodes.male_pants_3.geometry} material={materials.Palette} skeleton={nodes.male_pants_3.skeleton} morphTargetDictionary={nodes.male_pants_3.morphTargetDictionary} morphTargetInfluences={nodes.male_pants_3.morphTargetInfluences} />
      <skinnedMesh name="male_shirt_3" geometry={nodes.male_shirt_3.geometry} material={materials.Palette} skeleton={nodes.male_shirt_3.skeleton} morphTargetDictionary={nodes.male_shirt_3.morphTargetDictionary} morphTargetInfluences={nodes.male_shirt_3.morphTargetInfluences} />
      <skinnedMesh name="male_shoes_3" geometry={nodes.male_shoes_3.geometry} material={materials.Palette} skeleton={nodes.male_shoes_3.skeleton} morphTargetDictionary={nodes.male_shoes_3.morphTargetDictionary} morphTargetInfluences={nodes.male_shoes_3.morphTargetInfluences} /> */}
        </group>
    )
}

useGLTF.preload('/3D/male_4.gltf')
